### ISSUE TITLE
How to obtain a xptr on a compiled function

### ISSUE THREAD

**Issue by talegari** [Enchufa2/RcppXPtrUtils#1]
Hi,

Thanks for the handy package!

Question: I am using `parDist` from `parallelDist` package with my own distance function written in C++ in a package. `parallelDist` expects the user defined function to be a xptr from this package(`RcppXPtrUtils`).

Currently, `cppXPtr` seems to accept C++ code as a string. Whats the ideal way to pre-compile my distance function and eventually submit my package to CRAN?

Regards,
Srikanth KS

**Comment by Enchufa2** [comment]
`cppXPtr` is a wrapper around `Rcpp::cppFunction` that extracts the function signature and stores it as attributes (obviously, this can only be done if the C++ code is provided as a string), then the string is forwarded to `Rcpp::cppFunction` for compilation. This is intended for interactive usage, to enable early checks at R level and avoid nasty runtime errors.

But if you want to develop a package to enhance `parallelDist`, you know what you are doing. So you can check what `parallelDist` expects:

```r
library(RcppXPtrUtils)

# example from the parallelDist README
euclideanFuncPtr <- cppXPtr("
  double customDist(const arma::mat &A, const arma::mat &B) {
    return sqrt(arma::accu(arma::square(A - B)));
  }", depends = c("RcppArmadillo"))

attributes(euclideanFuncPtr)
#> $class
#> [1] "XPtr"
#> 
#> $type
#> [1] "double"
#> 
#> $fname
#> [1] "customDist"
#> 
#> $args
#> [1] "const arma::mat& A" "const arma::mat& B"
```

and set those attributes for your external pointers.

**Comment by talegari** [comment]
Thanks.
