### ISSUE TITLE
typo in signature checking

### ISSUE THREAD

**Issue by sgsokol** [Enchufa2/RcppXPtrUtils#2]
Trying an example from http://gallery.rcpp.org/articles/passing-cpp-function-pointers-rcppxptrutils/ I found what seems to be a typo for me:
```checkXPtr(ptr, "int", c("int", "double"))```
prints an error having the following text:
"Wrong return type 'double', should be 'int'"
where "double" and "int" are inverted. The right return type is "double" so it should read "Wrong return type 'int', should be 'double'"

**Comment by Enchufa2** [comment]
Indeed, they are reversed in the error message. Thanks for the report, Serguei.
